name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # Runs on every push to dev branch-

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Recreate Google Service Account Key
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" | base64 --decode > backend/service_account.json

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Debug Docker Username
        run: echo "Docker Username is ${{ secrets.DOCKER_USERNAME }}"
        
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/macro-api:latest ./backend

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/macro-api:latest
